name: Build Everything

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
    
jobs:
    linux-build:
      uses: ./.github/workflows/linux_build.yml
    macos-build:
      uses: ./.github/workflows/macos_build.yml
    windows_build:
      uses: ./.github/workflows/windows_build.yml 